INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1101', '11', 'KAB. ACEH SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1102', '11', 'KAB. ACEH TENGGARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1103', '11', 'KAB. ACEH TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1104', '11', 'KAB. ACEH TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1105', '11', 'KAB. ACEH BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1106', '11', 'KAB. ACEH BESAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1107', '11', 'KAB. PIDIE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1108', '11', 'KAB. ACEH UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1109', '11', 'KAB. SIMEULUE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1110', '11', 'KAB. ACEH SINGKIL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1111', '11', 'KAB. BIREUEN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1112', '11', 'KAB. ACEH BARAT DAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1113', '11', 'KAB. GAYO LUES');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1114', '11', 'KAB. ACEH JAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1115', '11', 'KAB. NAGAN RAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1116', '11', 'KAB. ACEH TAMIANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1117', '11', 'KAB. BENER MERIAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1118', '11', 'KAB. PIDIE JAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1171', '11', 'KOTA BANDA ACEH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1172', '11', 'KOTA SABANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1173', '11', 'KOTA LHOKSEUMAWE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1174', '11', 'KOTA LANGSA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1175', '11', 'KOTA SUBULUSSALAM');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1201', '12', 'KAB. TAPANULI TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1202', '12', 'KAB. TAPANULI UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1203', '12', 'KAB. TAPANULI SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1204', '12', 'KAB. NIAS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1205', '12', 'KAB. LANGKAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1206', '12', 'KAB. KARO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1207', '12', 'KAB. DELI SERDANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1208', '12', 'KAB. SIMALUNGUN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1209', '12', 'KAB. ASAHAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1210', '12', 'KAB. LABUHANBATU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1211', '12', 'KAB. DAIRI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1212', '12', 'KAB. TOBA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1213', '12', 'KAB. MANDAILING NATAL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1214', '12', 'KAB. NIAS SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1215', '12', 'KAB. PAKPAK BHARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1216', '12', 'KAB. HUMBANG HASUNDUTAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1217', '12', 'KAB. SAMOSIR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1218', '12', 'KAB. SERDANG BEDAGAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1219', '12', 'KAB. BATU BARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1220', '12', 'KAB. PADANG LAWAS UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1221', '12', 'KAB. PADANG LAWAS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1222', '12', 'KAB. LABUHANBATU SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1223', '12', 'KAB. LABUHANBATU UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1224', '12', 'KAB. NIAS UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1225', '12', 'KAB. NIAS BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1271', '12', 'KOTA MEDAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1272', '12', 'KOTA PEMATANGSIANTAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1273', '12', 'KOTA SIBOLGA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1274', '12', 'KOTA TANJUNG BALAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1275', '12', 'KOTA BINJAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1276', '12', 'KOTA TEBING TINGGI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1277', '12', 'KOTA PADANGSIDIMPUAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1278', '12', 'KOTA GUNUNGSITOLI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1301', '13', 'KAB. PESISIR SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1302', '13', 'KAB. SOLOK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1303', '13', 'KAB. SIJUNJUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1304', '13', 'KAB. TANAH DATAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1305', '13', 'KAB. PADANG PARIAMAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1306', '13', 'KAB. AGAM');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1307', '13', 'KAB. LIMA PULUH KOTA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1308', '13', 'KAB. PASAMAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1309', '13', 'KAB. KEPULAUAN MENTAWAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1310', '13', 'KAB. DHARMASRAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1311', '13', 'KAB. SOLOK SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1312', '13', 'KAB. PASAMAN BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1371', '13', 'KOTA PADANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1372', '13', 'KOTA SOLOK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1373', '13', 'KOTA SAWAHLUNTO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1374', '13', 'KOTA PADANG PANJANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1375', '13', 'KOTA BUKITTINGGI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1376', '13', 'KOTA PAYAKUMBUH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1377', '13', 'KOTA PARIAMAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1401', '14', 'KAB. KAMPAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1402', '14', 'KAB. INDRAGIRI HULU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1403', '14', 'KAB. BENGKALIS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1404', '14', 'KAB. INDRAGIRI HILIR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1405', '14', 'KAB. PELALAWAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1406', '14', 'KAB. ROKAN HULU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1407', '14', 'KAB. ROKAN HILIR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1408', '14', 'KAB. SIAK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1409', '14', 'KAB. KUANTAN SINGINGI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1410', '14', 'KAB. KEPULAUAN MERANTI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1471', '14', 'KOTA PEKANBARU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1472', '14', 'KOTA DUMAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1501', '15', 'KAB. KERINCI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1502', '15', 'KAB. MERANGIN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1503', '15', 'KAB. SAROLANGUN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1504', '15', 'KAB. BATANGHARI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1505', '15', 'KAB. MUARO JAMBI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1506', '15', 'KAB. TANJUNG JABUNG BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1507', '15', 'KAB. TANJUNG JABUNG TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1508', '15', 'KAB. BUNGO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1509', '15', 'KAB. TEBO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1571', '15', 'KOTA JAMBI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1572', '15', 'KOTA SUNGAI PENUH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1601', '16', 'KAB. OGAN KOMERING ULU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1602', '16', 'KAB. OGAN KOMERING ILIR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1603', '16', 'KAB. MUARA ENIM');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1604', '16', 'KAB. LAHAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1605', '16', 'KAB. MUSI RAWAS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1606', '16', 'KAB. MUSI BANYUASIN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1607', '16', 'KAB. BANYUASIN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1608', '16', 'KAB. OGAN KOMERING ULU TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1609', '16', 'KAB. OGAN KOMERING ULU SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1610', '16', 'KAB. OGAN ILIR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1611', '16', 'KAB. EMPAT LAWANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1612', '16', 'KAB. PENUKAL ABAB LEMATANG ILIR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1613', '16', 'KAB. MUSI RAWAS UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1671', '16', 'KOTA PALEMBANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1672', '16', 'KOTA PAGAR ALAM');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1673', '16', 'KOTA LUBUK LINGGAU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1674', '16', 'KOTA PRABUMULIH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1701', '17', 'KAB. BENGKULU SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1702', '17', 'KAB. REJANG LEBONG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1703', '17', 'KAB. BENGKULU UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1704', '17', 'KAB. KAUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1705', '17', 'KAB. SELUMA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1706', '17', 'KAB. MUKO MUKO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1707', '17', 'KAB. LEBONG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1708', '17', 'KAB. KEPAHIANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1709', '17', 'KAB. BENGKULU TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1771', '17', 'KOTA BENGKULU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1801', '18', 'KAB. LAMPUNG SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1802', '18', 'KAB. LAMPUNG TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1803', '18', 'KAB. LAMPUNG UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1804', '18', 'KAB. LAMPUNG BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1805', '18', 'KAB. TULANG BAWANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1806', '18', 'KAB. TANGGAMUS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1807', '18', 'KAB. LAMPUNG TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1808', '18', 'KAB. WAY KANAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1809', '18', 'KAB. PESAWARAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1810', '18', 'KAB. PRINGSEWU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1811', '18', 'KAB. MESUJI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1812', '18', 'KAB. TULANG BAWANG BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1813', '18', 'KAB. PESISIR BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1871', '18', 'KOTA BANDAR LAMPUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1872', '18', 'KOTA METRO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1901', '19', 'KAB. BANGKA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1902', '19', 'KAB. BELITUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1903', '19', 'KAB. BANGKA SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1904', '19', 'KAB. BANGKA TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1905', '19', 'KAB. BANGKA BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1906', '19', 'KAB. BELITUNG TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('1971', '19', 'KOTA PANGKAL PINANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('2101', '21', 'KAB. BINTAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('2102', '21', 'KAB. KARIMUN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('2103', '21', 'KAB. NATUNA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('2104', '21', 'KAB. LINGGA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('2105', '21', 'KAB. KEPULAUAN ANAMBAS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('2171', '21', 'KOTA BATAM');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('2172', '21', 'KOTA TANJUNG PINANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3101', '31', 'KAB. ADM. KEP. SERIBU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3171', '31', 'KOTA ADM. JAKARTA PUSAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3172', '31', 'KOTA ADM. JAKARTA UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3173', '31', 'KOTA ADM. JAKARTA BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3174', '31', 'KOTA ADM. JAKARTA SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3175', '31', 'KOTA ADM. JAKARTA TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3201', '32', 'KAB. BOGOR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3202', '32', 'KAB. SUKABUMI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3203', '32', 'KAB. CIANJUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3204', '32', 'KAB. BANDUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3205', '32', 'KAB. GARUT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3206', '32', 'KAB. TASIKMALAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3207', '32', 'KAB. CIAMIS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3208', '32', 'KAB. KUNINGAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3209', '32', 'KAB. CIREBON');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3210', '32', 'KAB. MAJALENGKA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3211', '32', 'KAB. SUMEDANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3212', '32', 'KAB. INDRAMAYU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3213', '32', 'KAB. SUBANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3214', '32', 'KAB. PURWAKARTA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3215', '32', 'KAB. KARAWANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3216', '32', 'KAB. BEKASI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3217', '32', 'KAB. BANDUNG BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3218', '32', 'KAB. PANGANDARAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3271', '32', 'KOTA BOGOR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3272', '32', 'KOTA SUKABUMI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3273', '32', 'KOTA BANDUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3274', '32', 'KOTA CIREBON');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3275', '32', 'KOTA BEKASI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3276', '32', 'KOTA DEPOK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3277', '32', 'KOTA CIMAHI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3278', '32', 'KOTA TASIKMALAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3279', '32', 'KOTA BANJAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3301', '33', 'KAB. CILACAP');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3302', '33', 'KAB. BANYUMAS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3303', '33', 'KAB. PURBALINGGA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3304', '33', 'KAB. BANJARNEGARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3305', '33', 'KAB. KEBUMEN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3306', '33', 'KAB. PURWOREJO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3307', '33', 'KAB. WONOSOBO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3308', '33', 'KAB. MAGELANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3309', '33', 'KAB. BOYOLALI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3310', '33', 'KAB. KLATEN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3311', '33', 'KAB. SUKOHARJO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3312', '33', 'KAB. WONOGIRI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3313', '33', 'KAB. KARANGANYAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3314', '33', 'KAB. SRAGEN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3315', '33', 'KAB. GROBOGAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3316', '33', 'KAB. BLORA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3317', '33', 'KAB. REMBANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3318', '33', 'KAB. PATI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3319', '33', 'KAB. KUDUS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3320', '33', 'KAB. JEPARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3321', '33', 'KAB. DEMAK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3322', '33', 'KAB. SEMARANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3323', '33', 'KAB. TEMANGGUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3324', '33', 'KAB. KENDAL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3325', '33', 'KAB. BATANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3326', '33', 'KAB. PEKALONGAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3327', '33', 'KAB. PEMALANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3328', '33', 'KAB. TEGAL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3329', '33', 'KAB. BREBES');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3371', '33', 'KOTA MAGELANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3372', '33', 'KOTA SURAKARTA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3373', '33', 'KOTA SALATIGA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3374', '33', 'KOTA SEMARANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3375', '33', 'KOTA PEKALONGAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3376', '33', 'KOTA TEGAL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3401', '34', 'KAB. KULON PROGO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3402', '34', 'KAB. BANTUL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3403', '34', 'KAB. GUNUNGKIDUL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3404', '34', 'KAB. SLEMAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3471', '34', 'KOTA YOGYAKARTA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3501', '35', 'KAB. PACITAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3502', '35', 'KAB. PONOROGO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3503', '35', 'KAB. TRENGGALEK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3504', '35', 'KAB. TULUNGAGUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3505', '35', 'KAB. BLITAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3506', '35', 'KAB. KEDIRI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3507', '35', 'KAB. MALANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3508', '35', 'KAB. LUMAJANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3509', '35', 'KAB. JEMBER');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3510', '35', 'KAB. BANYUWANGI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3511', '35', 'KAB. BONDOWOSO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3512', '35', 'KAB. SITUBONDO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3513', '35', 'KAB. PROBOLINGGO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3514', '35', 'KAB. PASURUAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3515', '35', 'KAB. SIDOARJO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3516', '35', 'KAB. MOJOKERTO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3517', '35', 'KAB. JOMBANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3518', '35', 'KAB. NGANJUK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3519', '35', 'KAB. MADIUN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3520', '35', 'KAB. MAGETAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3521', '35', 'KAB. NGAWI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3522', '35', 'KAB. BOJONEGORO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3523', '35', 'KAB. TUBAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3524', '35', 'KAB. LAMONGAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3525', '35', 'KAB. GRESIK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3526', '35', 'KAB. BANGKALAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3527', '35', 'KAB. SAMPANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3528', '35', 'KAB. PAMEKASAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3529', '35', 'KAB. SUMENEP');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3571', '35', 'KOTA KEDIRI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3572', '35', 'KOTA BLITAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3573', '35', 'KOTA MALANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3574', '35', 'KOTA PROBOLINGGO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3575', '35', 'KOTA PASURUAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3576', '35', 'KOTA MOJOKERTO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3577', '35', 'KOTA MADIUN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3578', '35', 'KOTA SURABAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3579', '35', 'KOTA BATU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3601', '36', 'KAB. PANDEGLANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3602', '36', 'KAB. LEBAK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3603', '36', 'KAB. TANGERANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3604', '36', 'KAB. SERANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3671', '36', 'KOTA TANGERANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3672', '36', 'KOTA CILEGON');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3673', '36', 'KOTA SERANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('3674', '36', 'KOTA TANGERANG SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5101', '51', 'KAB. JEMBRANA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5102', '51', 'KAB. TABANAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5103', '51', 'KAB. BADUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5104', '51', 'KAB. GIANYAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5105', '51', 'KAB. KLUNGKUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5106', '51', 'KAB. BANGLI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5107', '51', 'KAB. KARANGASEM');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5108', '51', 'KAB. BULELENG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5171', '51', 'KOTA DENPASAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5201', '52', 'KAB. LOMBOK BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5202', '52', 'KAB. LOMBOK TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5203', '52', 'KAB. LOMBOK TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5204', '52', 'KAB. SUMBAWA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5205', '52', 'KAB. DOMPU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5206', '52', 'KAB. BIMA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5207', '52', 'KAB. SUMBAWA BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5208', '52', 'KAB. LOMBOK UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5271', '52', 'KOTA MATARAM');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5272', '52', 'KOTA BIMA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5301', '53', 'KAB. KUPANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5302', '53', 'KAB TIMOR TENGAH SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5303', '53', 'KAB. TIMOR TENGAH UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5304', '53', 'KAB. BELU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5305', '53', 'KAB. ALOR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5306', '53', 'KAB. FLORES TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5307', '53', 'KAB. SIKKA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5308', '53', 'KAB. ENDE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5309', '53', 'KAB. NGADA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5310', '53', 'KAB. MANGGARAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5311', '53', 'KAB. SUMBA TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5312', '53', 'KAB. SUMBA BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5313', '53', 'KAB. LEMBATA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5314', '53', 'KAB. ROTE NDAO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5315', '53', 'KAB. MANGGARAI BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5316', '53', 'KAB. NAGEKEO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5317', '53', 'KAB. SUMBA TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5318', '53', 'KAB. SUMBA BARAT DAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5319', '53', 'KAB. MANGGARAI TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5320', '53', 'KAB. SABU RAIJUA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5321', '53', 'KAB. MALAKA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('5371', '53', 'KOTA KUPANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6101', '61', 'KAB. SAMBAS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6102', '61', 'KAB. MEMPAWAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6103', '61', 'KAB. SANGGAU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6104', '61', 'KAB. KETAPANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6105', '61', 'KAB. SINTANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6106', '61', 'KAB. KAPUAS HULU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6107', '61', 'KAB. BENGKAYANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6108', '61', 'KAB. LANDAK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6109', '61', 'KAB. SEKADAU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6110', '61', 'KAB. MELAWI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6111', '61', 'KAB. KAYONG UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6112', '61', 'KAB. KUBU RAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6171', '61', 'KOTA PONTIANAK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6172', '61', 'KOTA SINGKAWANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6201', '62', 'KAB. KOTAWARINGIN BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6202', '62', 'KAB. KOTAWARINGIN TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6203', '62', 'KAB. KAPUAS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6204', '62', 'KAB. BARITO SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6205', '62', 'KAB. BARITO UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6206', '62', 'KAB. KATINGAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6207', '62', 'KAB. SERUYAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6208', '62', 'KAB. SUKAMARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6209', '62', 'KAB. LAMANDAU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6210', '62', 'KAB. GUNUNG MAS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6211', '62', 'KAB. PULANG PISAU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6212', '62', 'KAB. MURUNG RAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6213', '62', 'KAB. BARITO TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6271', '62', 'KOTA PALANGKARAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6301', '63', 'KAB. TANAH LAUT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6302', '63', 'KAB. KOTABARU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6303', '63', 'KAB. BANJAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6304', '63', 'KAB. BARITO KUALA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6305', '63', 'KAB. TAPIN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6306', '63', 'KAB. HULU SUNGAI SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6307', '63', 'KAB. HULU SUNGAI TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6308', '63', 'KAB. HULU SUNGAI UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6309', '63', 'KAB. TABALONG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6310', '63', 'KAB. TANAH BUMBU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6311', '63', 'KAB. BALANGAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6371', '63', 'KOTA BANJARMASIN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6372', '63', 'KOTA BANJARBARU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6401', '64', 'KAB. PASER');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6402', '64', 'KAB. KUTAI KARTANEGARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6403', '64', 'KAB. BERAU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6407', '64', 'KAB. KUTAI BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6408', '64', 'KAB. KUTAI TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6409', '64', 'KAB. PENAJAM PASER UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6411', '64', 'KAB. MAHAKAM ULU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6471', '64', 'KOTA BALIKPAPAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6472', '64', 'KOTA SAMARINDA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6474', '64', 'KOTA BONTANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6501', '65', 'KAB. BULUNGAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6502', '65', 'KAB. MALINAU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6503', '65', 'KAB. NUNUKAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6504', '65', 'KAB. TANA TIDUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('6571', '65', 'KOTA TARAKAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7101', '71', 'KAB. BOLAANG MONGONDOW');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7102', '71', 'KAB. MINAHASA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7103', '71', 'KAB. KEPULAUAN SANGIHE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7104', '71', 'KAB. KEPULAUAN TALAUD');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7105', '71', 'KAB. MINAHASA SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7106', '71', 'KAB. MINAHASA UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7107', '71', 'KAB. MINAHASA TENGGARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7108', '71', 'KAB. BOLAANG MONGONDOW UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7109', '71', 'KAB. KEP. SIAU TAGULANDANG BIARO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7110', '71', 'KAB. BOLAANG MONGONDOW TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7111', '71', 'KAB. BOLAANG MONGONDOW SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7171', '71', 'KOTA MANADO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7172', '71', 'KOTA BITUNG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7173', '71', 'KOTA TOMOHON');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7174', '71', 'KOTA KOTAMOBAGU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7201', '72', 'KAB. BANGGAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7202', '72', 'KAB. POSO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7203', '72', 'KAB. DONGGALA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7204', '72', 'KAB. TOLI TOLI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7205', '72', 'KAB. BUOL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7206', '72', 'KAB. MOROWALI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7207', '72', 'KAB. BANGGAI KEPULAUAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7208', '72', 'KAB. PARIGI MOUTONG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7209', '72', 'KAB. TOJO UNA UNA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7210', '72', 'KAB. SIGI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7211', '72', 'KAB. BANGGAI LAUT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7212', '72', 'KAB. MOROWALI UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7271', '72', 'KOTA PALU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7301', '73', 'KAB. KEPULAUAN SELAYAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7302', '73', 'KAB. BULUKUMBA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7303', '73', 'KAB. BANTAENG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7304', '73', 'KAB. JENEPONTO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7305', '73', 'KAB. TAKALAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7306', '73', 'KAB. GOWA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7307', '73', 'KAB. SINJAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7308', '73', 'KAB. BONE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7309', '73', 'KAB. MAROS');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7310', '73', 'KAB. PANGKAJENE KEPULAUAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7311', '73', 'KAB. BARRU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7312', '73', 'KAB. SOPPENG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7313', '73', 'KAB. WAJO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7314', '73', 'KAB. SIDENRENG RAPPANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7315', '73', 'KAB. PINRANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7316', '73', 'KAB. ENREKANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7317', '73', 'KAB. LUWU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7318', '73', 'KAB. TANA TORAJA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7322', '73', 'KAB. LUWU UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7324', '73', 'KAB. LUWU TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7326', '73', 'KAB. TORAJA UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7371', '73', 'KOTA MAKASSAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7372', '73', 'KOTA PARE PARE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7373', '73', 'KOTA PALOPO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7401', '74', 'KAB. KOLAKA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7402', '74', 'KAB. KONAWE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7403', '74', 'KAB. MUNA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7404', '74', 'KAB. BUTON');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7405', '74', 'KAB. KONAWE SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7406', '74', 'KAB. BOMBANA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7407', '74', 'KAB. WAKATOBI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7408', '74', 'KAB. KOLAKA UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7409', '74', 'KAB. KONAWE UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7410', '74', 'KAB. BUTON UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7411', '74', 'KAB. KOLAKA TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7412', '74', 'KAB. KONAWE KEPULAUAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7413', '74', 'KAB. MUNA BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7414', '74', 'KAB. BUTON TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7415', '74', 'KAB. BUTON SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7471', '74', 'KOTA KENDARI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7472', '74', 'KOTA BAU BAU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7501', '75', 'KAB. GORONTALO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7502', '75', 'KAB. BOALEMO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7503', '75', 'KAB. BONE BOLANGO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7504', '75', 'KAB. POHUWATO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7505', '75', 'KAB. GORONTALO UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7571', '75', 'KOTA GORONTALO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7601', '76', 'KAB. PASANGKAYU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7602', '76', 'KAB. MAMUJU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7603', '76', 'KAB. MAMASA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7604', '76', 'KAB. POLEWALI MANDAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7605', '76', 'KAB. MAJENE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('7606', '76', 'KAB. MAMUJU TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8101', '81', 'KAB. MALUKU TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8102', '81', 'KAB. MALUKU TENGGARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8103', '81', 'KAB. KEPULAUAN TANIMBAR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8104', '81', 'KAB. BURU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8105', '81', 'KAB. SERAM BAGIAN TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8106', '81', 'KAB. SERAM BAGIAN BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8107', '81', 'KAB. KEPULAUAN ARU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8108', '81', 'KAB. MALUKU BARAT DAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8109', '81', 'KAB. BURU SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8171', '81', 'KOTA AMBON');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8172', '81', 'KOTA TUAL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8201', '82', 'KAB. HALMAHERA BARAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8202', '82', 'KAB. HALMAHERA TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8203', '82', 'KAB. HALMAHERA UTARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8204', '82', 'KAB. HALMAHERA SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8205', '82', 'KAB. KEPULAUAN SULA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8206', '82', 'KAB. HALMAHERA TIMUR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8207', '82', 'KAB. PULAU MOROTAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8208', '82', 'KAB. PULAU TALIABU');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8271', '82', 'KOTA TERNATE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('8272', '82', 'KOTA TIDORE KEPULAUAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9103', '91', 'KAB. JAYAPURA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9105', '91', 'KAB. KEPULAUAN YAPEN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9106', '91', 'KAB. BIAK NUMFOR');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9110', '91', 'KAB. SARMI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9111', '91', 'KAB. KEEROM');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9115', '91', 'KAB. WAROPEN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9119', '91', 'KAB. SUPIORI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9120', '91', 'KAB. MAMBERAMO RAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9171', '91', 'KOTA JAYAPURA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9201', '92', 'KAB. SORONG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9202', '92', 'KAB. MANOKWARI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9203', '92', 'KAB. FAK FAK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9204', '92', 'KAB. SORONG SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9205', '92', 'KAB. RAJA AMPAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9206', '92', 'KAB. TELUK BINTUNI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9207', '92', 'KAB. TELUK WONDAMA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9208', '92', 'KAB. KAIMANA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9209', '92', 'KAB. TAMBRAUW');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9210', '92', 'KAB. MAYBRAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9211', '92', 'KAB. MANOKWARI SELATAN');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9212', '92', 'KAB. PEGUNUNGAN ARFAK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9271', '92', 'KOTA SORONG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9301', '93', 'KAB. MERAUKE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9302', '93', 'KAB. BOVEN DIGOEL');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9303', '93', 'KAB. MAPPI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9304', '93', 'KAB. ASMAT');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9401', '94', 'KAB. NABIRE');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9402', '94', 'KAB. PUNCAK JAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9403', '94', 'KAB. PANIAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9404', '94', 'KAB. MIMIKA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9405', '94', 'KAB. PUNCAK');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9406', '94', 'KAB. DOGIYAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9407', '94', 'KAB. INTAN JAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9408', '94', 'KAB. DEIYAI');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9501', '95', 'KAB. JAYAWIJAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9502', '95', 'KAB. PEGUNUNGAN BINTANG');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9503', '95', 'KAB. YAHUKIMO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9504', '95', 'KAB. TOLIKARA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9505', '95', 'KAB. MAMBERAMO TENGAH');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9506', '95', 'KAB. YALIMO');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9507', '95', 'KAB. LANNY JAYA');
INSERT INTO `tujuans` (`id`, `province_id`, `nama_tujuan`) VALUES ('9508', '95', 'KAB. NDUGA');
